/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package reg_v;



import com.toedter.calendar.JTextFieldDateEditor;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;







/**
 *
 * @author erickarias
 */
public class n_clie extends javax.swing.JFrame {
    
  
    /**
     * Creates new form n_clie
     */
   
    public n_clie() {
        initComponents();
        this.setLocationRelativeTo(null);
        ((JTextFieldDateEditor)t_fecha.getDateEditor()).setEditable(false);
        
       /** try {
            String formato = comboFormato.getSelectedItem().toString();
            //Formato
            Date fecha = jDatefecha.getDate();
            SimpleDateFormat sdf = new SimpleDateFormat(formato);
            txtFechaSeleccionada.setText(sdf.format(fecha));
            jtxtescribe.setText(sdf.format(fecha));
          

        } catch(NullPointerException ex) {
            txtFechaSeleccionada.setText("");

        JOptionPane.showMessageDialog(this, "Al menos selecciona una fecha válida!", "Error!", JOptionPane.ERROR_MESSAGE);
     }//*/
        

    }
        
    
    void limpiar ()  { 
             t_fecha.setDate(null);
             t_nom.setText("");
             t_ape.setText("");
             t_dni.setText("");
             t_dir.setText("");
             t_mail.setText("");
             t_tel.setText("");
             t_cell.setText("");
             t_ta.setText("");
             t_re.setText("");
             
           
    }
         
         
        
                 
        void consultar (String d){
       
        acceso_java cc = new acceso_java ();
        Connection cn = cc.conxion();
        String cap="";
       
        
        String sql= "SELECT * FROM reg_tarj WHERE dni = '"+d+"'";
        
        try{
            
         Statement st = cn.createStatement();
         ResultSet rs = st.executeQuery(sql);
         
         while(rs.next ()){
             cap = rs.getString("dni");
             
          }
           if (t_dni.getText().equals(cap)){
 
               JOptionPane.showMessageDialog(null,"USUARIO YA REGISTRADO","Error",JOptionPane.ERROR_MESSAGE);
               System.exit(0);
               
             }
                
         
         }catch (SQLException ex) {
            Logger.getLogger(n_clie.class.getName()).log(Level.SEVERE, null, ex);
            
        }  
    }
               
                 
                 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        t_dir = new javax.swing.JTextField();
        t_mail = new javax.swing.JTextField();
        t_tel = new javax.swing.JTextField();
        t_cell = new javax.swing.JTextField();
        t_ta = new javax.swing.JTextField();
        t_dni = new javax.swing.JTextField();
        t_ape = new javax.swing.JTextField();
        t_nom = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        ing_bd = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        t_fecha = new com.toedter.calendar.JDateChooser();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        t_re = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(0, 153, 153));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Antonio", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("DNI");

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Antonio", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Correo");

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Antonio", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Direccion");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Antonio", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Apellido");

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Antonio", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombre");

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Antonio", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Cell.");

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Antonio", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Telf.");

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Antonio", 0, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Nro. Tarjeta");

        t_tel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_telKeyTyped(evt);
            }
        });

        t_cell.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_cellKeyTyped(evt);
            }
        });

        t_dni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_dniKeyTyped(evt);
            }
        });

        t_ape.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        t_ape.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_apeActionPerformed(evt);
            }
        });
        t_ape.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_apeKeyTyped(evt);
            }
        });

        t_nom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_nomKeyTyped(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(0, 77, 138));

        jLabel11.setBackground(new java.awt.Color(102, 102, 102));
        jLabel11.setFont(new java.awt.Font("Antonio", 0, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Nuevo cliente");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 13, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(10, 10, 10))
        );

        ing_bd.setText("Agregar");
        ing_bd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ing_bdMouseClicked(evt);
            }
        });
        ing_bd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ing_bdActionPerformed(evt);
            }
        });

        jButton3.setText("Linpiar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Antonio", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("FECHA");

        t_fecha.setDateFormatString("dd-MM-yyyy");

        jPanel2.setBackground(new java.awt.Color(127, 199, 95));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Antonio", 0, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Referido de");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9)
                                .addComponent(jLabel7)
                                .addComponent(jLabel6)
                                .addComponent(jLabel4)
                                .addComponent(jLabel8)
                                .addComponent(jLabel2)
                                .addComponent(jLabel1)
                                .addComponent(jLabel3)
                                .addComponent(jLabel10))
                            .addGap(52, 52, 52)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(t_nom, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(t_ape, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(t_dir, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(t_ta, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(t_mail, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(t_dni, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(t_cell, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(t_tel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(t_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(t_re, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ing_bd)))
                .addGap(22, 22, 22))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(t_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(t_ape, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(t_dni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(t_dir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(t_mail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(t_tel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(t_cell, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(t_ta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(t_re, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ing_bd)
                    .addComponent(jButton3))
                .addGap(17, 17, 17)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ing_bdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ing_bdActionPerformed
        // TODO add your handling code here:
        

   if (t_fecha.getDate()==null) { 
         
          JOptionPane.showMessageDialog(null,"NO OLVIDES LA FECHA","Error",JOptionPane.ERROR_MESSAGE);
          
    }      
          
   else if (t_nom.getText().isEmpty()) { 
         
          JOptionPane.showMessageDialog(null,"Ups... tienes que Colocar Nombre","Error",JOptionPane.ERROR_MESSAGE);
    
     } 
        
    else if (t_ape.getText().isEmpty()) { 
         
          JOptionPane.showMessageDialog(null,"Ups... tienes que Colocar Apellido","Error",JOptionPane.ERROR_MESSAGE);
         
         
     }
    
    else if (t_dni.getText().isEmpty()) { 
         
          JOptionPane.showMessageDialog(null,"Ups... tienes que Colocar DNI","Error",JOptionPane.ERROR_MESSAGE);
         
         
    }
    
    else if (t_dir.getText().isEmpty()) { 
         
          JOptionPane.showMessageDialog(null,"Ups... tienes que Colocar Dirección","Error",JOptionPane.ERROR_MESSAGE);
         
         
    }
    
    else if (t_tel.getText().isEmpty() && t_cell.getText().isEmpty()) {
        
         JOptionPane.showMessageDialog(null,"Ups... Ingresa algun numero telefonico","Error",JOptionPane.ERROR_MESSAGE);
    
     }
 
    else if (t_ta.getText().isEmpty()) { 
         
          JOptionPane.showMessageDialog(null,"INGRESA EL CODIGO DE BARRA DE LA TARJETA","Error",JOptionPane.ERROR_MESSAGE);
         

    }else{
        
        if (JOptionPane.showConfirmDialog(null,"CONFIRMA QUE LOS DATOS ESTEN CORRECTOS","CONFIRMAR",1)==0){ 
            
            
        String d = t_dni.getText();
        consultar(d);  
        SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
        acceso_java cc = new acceso_java ();
        Connection cn = cc.conxion();
        String sql="";
        String nom,ape,dni,dire,cor,tel,cel,fecha,nt,mc,re;
        nom = t_nom.getText();
        ape = t_ape.getText();
        dni = t_dni.getText();
        dire = t_dir.getText();
        cor = t_mail.getText();
        tel = t_tel.getText();
        cel = t_cell.getText();
        String fechad = sdf.format(t_fecha.getDate()); 
        nt = t_ta.getText();
        re = t_re.getText();
        
        
     
        
        sql= "INSERT INTO reg_tarj (nom,ape,dni,dir,mail,tel,cell,fecha,nt,re_d) VALUES(?,?,?,?,?,?,?,?,?,?)";
        
        try{
            
          PreparedStatement pst = cn.prepareStatement(sql);
           
           pst.setString(1,nom);
           pst.setString(2,ape);
           pst.setString(3,dni);
           pst.setString(4,dire);
           pst.setString(5,cor);
           pst.setString(6,tel);
           pst.setString(7,cel);
           pst.setString(8,fechad);
           pst.setString(9,nt);
           pst.setString(10,re);
           
           
           int n=pst.executeUpdate();
           if (n>0){
               JOptionPane.showMessageDialog(null,"Registro Guardado con Exito");
               limpiar();
               
           }
                 
                 
        }catch (SQLException ex) {
            Logger.getLogger(n_clie.class.getName()).log(Level.SEVERE, null, ex);
            
        }
    }//GEN-LAST:event_ing_bdActionPerformed
   } 
 } 
  
 
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        limpiar();
        
     
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void ing_bdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ing_bdMouseClicked
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_ing_bdMouseClicked

    private void t_dniKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_dniKeyTyped
        // TODO add your handling code here:
         char car = evt.getKeyChar();
        if( t_dni.getText().length()>=15 ) evt.consume();
        if(( car<'0' || car>'9' )) evt.consume();
        
    }//GEN-LAST:event_t_dniKeyTyped

    private void t_telKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_telKeyTyped
        // TODO add your handling code here:
         char car = evt.getKeyChar();
        if( t_tel.getText().length()>=15 ) evt.consume();
        if(( car<'0' || car>'9' )) evt.consume();
    }//GEN-LAST:event_t_telKeyTyped

    private void t_cellKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_cellKeyTyped
        // TODO add your handling code here:
         char car = evt.getKeyChar();
        if( t_cell.getText().length()>=15 ) evt.consume();
        if(( car<'0' || car>'9' )) evt.consume();
    }//GEN-LAST:event_t_cellKeyTyped

    private void t_apeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_apeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_apeActionPerformed

    private void t_nomKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_nomKeyTyped
        // TODO add your handling code here:
        
        char c; 
        c=evt.getKeyChar(); 
        if(!(c<'0'||c>'9')) 
        evt.consume(); 
    }//GEN-LAST:event_t_nomKeyTyped

    private void t_apeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_apeKeyTyped
        // TODO add your handling code here:
        
        char c; 
        c=evt.getKeyChar(); 
        if(!(c<'0'||c>'9')) 
        evt.consume(); 
    }//GEN-LAST:event_t_apeKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(n_clie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(n_clie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(n_clie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(n_clie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new n_clie().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ing_bd;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField t_ape;
    private javax.swing.JTextField t_cell;
    private javax.swing.JTextField t_dir;
    private javax.swing.JTextField t_dni;
    private com.toedter.calendar.JDateChooser t_fecha;
    private javax.swing.JTextField t_mail;
    private javax.swing.JTextField t_nom;
    private javax.swing.JTextField t_re;
    private javax.swing.JTextField t_ta;
    private javax.swing.JTextField t_tel;
    // End of variables declaration//GEN-END:variables
}
