/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package reg_v;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author erickarias
 */
public class n_compra extends javax.swing.JFrame {

    /**
     * Creates new form n_compra
     */
    public n_compra() {
        initComponents();
        this.setLocationRelativeTo(null);
        n_label.setForeground(Color.white); 
        a_label.setForeground(Color.white); 
        dni_label.setForeground(Color.white); 
  
     
     }
       void cerrar() {
           
         n_compra close = new n_compra();
         close.setVisible(false);
        
    }
        
   
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        t_cr = new javax.swing.JButton();
        t_mc = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        n_label = new javax.swing.JLabel();
        a_label = new javax.swing.JLabel();
        dni_label = new javax.swing.JLabel();
        t_ct = new javax.swing.JTextField();

        jTextField2.setText("jTextField2");

        jPanel8.setBackground(new java.awt.Color(0, 77, 138));

        jLabel13.setBackground(new java.awt.Color(102, 102, 102));
        jLabel13.setFont(new java.awt.Font("Antonio", 0, 20)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Nueva Compra");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(0, 13, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(10, 10, 10))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(0, 153, 153));

        jPanel6.setBackground(new java.awt.Color(0, 77, 138));

        jLabel11.setBackground(new java.awt.Color(102, 102, 102));
        jLabel11.setFont(new java.awt.Font("Antonio", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Nueva Compra");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 13, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(10, 10, 10))
        );

        t_cr.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        t_cr.setText("CARGAR REGISTRO");
        t_cr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_crActionPerformed(evt);
            }
        });

        t_mc.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        t_mc.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t_mc.setToolTipText("");
        t_mc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_mcActionPerformed(evt);
            }
        });
        t_mc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_mcKeyTyped(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                t_mcKeyReleased(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(127, 199, 95));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 469, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        n_label.setBackground(new java.awt.Color(153, 153, 153));
        n_label.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        n_label.setText("_______________________");
        n_label.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        a_label.setBackground(new java.awt.Color(153, 153, 153));
        a_label.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        a_label.setText("_______________________");

        dni_label.setBackground(new java.awt.Color(153, 153, 153));
        dni_label.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        dni_label.setText("_______________________");

        t_ct.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        t_ct.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t_ct.setToolTipText("");
        t_ct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_ctActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(dni_label)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(a_label, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(n_label, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(t_cr, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(t_ct, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t_mc, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(n_label, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(a_label, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(dni_label, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(t_ct, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(t_mc, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(t_cr, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void t_crActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_crActionPerformed
        // TODO add your handling code here:
        
        if(t_ct.getText().isEmpty()) { 
            
            JOptionPane.showMessageDialog(null,"INGRESA EL CODIGO DE LA TARJETA","Error",JOptionPane.ERROR_MESSAGE);
        }
        
        else if (t_mc.getText().isEmpty()) {
            
            JOptionPane.showMessageDialog(null,"INGRESA EL MONTO DE COMPRA","Error",JOptionPane.ERROR_MESSAGE);
            
        }else{
        
            if (JOptionPane.showConfirmDialog(null,"CONFIRMA QUE LOS DATOS ESTEN CORRECTOS","CONFIRMAR",1)==0){ 
                
                acceso_java cc = new acceso_java ();
                Connection cn = cc.conxion();
                String sql="";
                String nom,ape,dni,nt,mc;
                 nom = n_label.getText();
                 ape = a_label.getText();
                 dni = dni_label.getText();
                 nt = t_ct.getText();
                 mc = t_mc.getText();
                
             sql = "INSERT INTO t_compras (n_clie,a_clie,dni_clie,t_clie,t_mc) VALUES(?,?,?,?,?)";
             
             try{
                 
               PreparedStatement pst = cn.prepareStatement(sql); 
               pst.setString(1,nom);
               pst.setString(2,ape);
               pst.setString(3,dni);
               pst.setString(4,nt);
               pst.setString(5,mc);
               
               int n=pst.executeUpdate();
               
               if (n>0){
               JOptionPane.showMessageDialog(null,"Registro Guardado con Exito");
                this.setVisible(false);
                reg_tarj.t_fecha.setText("");
                reg_tarj.t_nom.setText("");
                reg_tarj.t_ape.setText("");
                reg_tarj.t_dni.setText("");
                reg_tarj.t_dir.setText("");
                reg_tarj.t_mail.setText("");
                reg_tarj.t_tel.setText("");
                reg_tarj.t_cell.setText("");
                reg_tarj.t_nt.setText("");
                 
               
                 }
             }catch (SQLException ex){
                 Logger.getLogger(n_clie.class.getName()).log(Level.SEVERE, null, ex); 
                this.setVisible(false);
                reg_tarj.t_fecha.setText("");
                reg_tarj.t_nom.setText("");
                reg_tarj.t_ape.setText("");
                reg_tarj.t_dni.setText("");
                reg_tarj.t_dir.setText("");
                reg_tarj.t_mail.setText("");
                reg_tarj.t_tel.setText("");
                reg_tarj.t_cell.setText("");
                reg_tarj.t_nt.setText("");
                 
             }
               
                 
                 
           }
        
         }
                
                
                
                
    }//GEN-LAST:event_t_crActionPerformed

    private void t_mcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_mcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_mcActionPerformed

    private void t_ctActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_ctActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_ctActionPerformed

    private void t_mcKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_mcKeyTyped
        // TODO add your handling code here:
        
        if (!Character.isDigit(evt.getKeyChar())&&evt.getKeyChar()!='.'){

            evt.consume();

        }

        else if(evt.getKeyChar()=='.'&&t_mc.getText().contains(".")){

            evt.consume();

        }
        
    }//GEN-LAST:event_t_mcKeyTyped

    private void t_mcKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_mcKeyReleased
        // TODO add your handling code here:
            if(String.valueOf(t_mc.getText().charAt(0)).equals(".")){
            t_mc.setText("0.");

        }
        
    }//GEN-LAST:event_t_mcKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(n_compra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(n_compra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(n_compra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(n_compra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new n_compra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel a_label;
    public static javax.swing.JLabel dni_label;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTextField jTextField2;
    public static javax.swing.JLabel n_label;
    private javax.swing.JButton t_cr;
    private javax.swing.JTextField t_ct;
    private javax.swing.JTextField t_mc;
    // End of variables declaration//GEN-END:variables
}
