/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package reg_v;

import com.toedter.calendar.JTextFieldDateEditor;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author erickarias
 */
public class user extends javax.swing.JFrame {

    /**
     * Creates new form user
     */
    public user() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(new Color (0, 153, 153));
        ((JTextFieldDateEditor)t_fecha.getDateEditor()).setEditable(false);

    }

    void consultar (String d){
       
        acceso_java cc = new acceso_java ();
        Connection cn = cc.conxion();
        String cap="";
       
        
        String sql= "SELECT * FROM usuario WHERE dni = '"+d+"'";
        
        try{
            
         Statement st = cn.createStatement();
         ResultSet rs = st.executeQuery(sql);
         
         while(rs.next ()){
             cap = rs.getString("dni");
             
          }
           if (t_dni.getText().equals(cap)){
 
               JOptionPane.showMessageDialog(null,"USUARIO YA REGISTRADO","Error",JOptionPane.ERROR_MESSAGE);
               System.exit(0);
               
             }
                
         
         }catch (SQLException ex) {
            Logger.getLogger(n_clie.class.getName()).log(Level.SEVERE, null, ex);
            
        }
          
    }
    
     void consultar2(String n){
       
        acceso_java cc = new acceso_java ();
        Connection cn = cc.conxion();
        String cap="";
       
        
        String sql= "SELECT * FROM usuario WHERE nick = '"+n+"'";
        
        try{
            
         Statement st = cn.createStatement();
         ResultSet rs = st.executeQuery(sql);
         
         while(rs.next ()){
             cap = rs.getString("nick");
             
          }
           if (t_us.getText().equals(cap)){
 
               JOptionPane.showMessageDialog(null,"USUARIO YA ESTA EN USO","Error",JOptionPane.ERROR_MESSAGE);
               String ax = JOptionPane.showInputDialog("Ingresa un nombre de usuario diferente");
               t_us.setText(ax);
               String nus = t_us.getText();
               consultar2(nus);
               //JOptionPane.showInputDialog(null,"El nickingresado es" +ax);
             }
                
                
         }catch (SQLException ex) {
            Logger.getLogger(n_clie.class.getName()).log(Level.SEVERE, null, ex);
            
        }
          
    }
    
    
    
    void limpiar (){
        
       t_fecha.setDate(null);
       t_nom.setText("");
       t_ape.setText("");
       t_dni.setText("");
       t_us.setText("");
       t_pass.setText("");
       c_tie.setSelectedItem("Escoja una");
       c_us.setSelectedItem("Escoja un");

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        t_fecha = new com.toedter.calendar.JDateChooser();
        t_ape = new javax.swing.JTextField();
        t_dni = new javax.swing.JTextField();
        t_us = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        cu = new javax.swing.JButton();
        t_nom = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        c_us = new javax.swing.JComboBox();
        t_pass = new javax.swing.JPasswordField();
        jLabel15 = new javax.swing.JLabel();
        c_tie = new javax.swing.JComboBox();

        jPanel6.setBackground(new java.awt.Color(0, 77, 138));

        jLabel12.setBackground(new java.awt.Color(102, 102, 102));
        jLabel12.setFont(new java.awt.Font("Antonio", 0, 20)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Editar Registros");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 13, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(10, 10, 10))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Antonio", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Apellido");

        jPanel2.setBackground(new java.awt.Color(127, 199, 95));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 301, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Antonio", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombre");

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Antonio", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("DNI");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Antonio", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("FECHA");

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Antonio", 0, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Usuario");

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Antonio", 0, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Contraseña");

        t_ape.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_apeKeyTyped(evt);
            }
        });

        t_dni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_dniKeyTyped(evt);
            }
        });

        jPanel7.setBackground(new java.awt.Color(0, 77, 138));

        jLabel13.setBackground(new java.awt.Color(102, 102, 102));
        jLabel13.setFont(new java.awt.Font("Antonio", 0, 20)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Nuevo Usuario");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(0, 13, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(10, 10, 10))
        );

        cu.setText("Crear");
        cu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuActionPerformed(evt);
            }
        });

        t_nom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_nomKeyTyped(evt);
            }
        });

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Antonio", 0, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Tipo");

        c_us.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Escoja un", "Administrador", "Caja", "Todos" }));

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Antonio", 0, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Tienda");

        c_tie.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Escoja una", "Tienda Rey", "Tienda Barranca", "Tienda Canepa", "Tienda Magdalena", " ", " " }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel10))
                                .addGap(35, 35, 35))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(t_ape)
                                .addComponent(t_dni, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(t_us, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(t_nom, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(t_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(t_pass, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(c_us, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(c_tie, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(cu))
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(t_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(t_nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(t_ape, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(t_dni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(t_us, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(t_pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(c_tie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(c_us, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 24, Short.MAX_VALUE)
                .addComponent(cu)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuActionPerformed
  
    if (t_fecha.getDate()==null) { 
         
          JOptionPane.showMessageDialog(null,"NO OLVIDES LA FECHA","Error",JOptionPane.ERROR_MESSAGE);
          
    }      
          
   else if (t_nom.getText().isEmpty()) { 
         
          JOptionPane.showMessageDialog(null,"Ups... tienes que Colocar Nombre","Error",JOptionPane.ERROR_MESSAGE);
    
     } 
   
   else if (t_ape.getText().isEmpty()) { 
         
          JOptionPane.showMessageDialog(null,"Ups... tienes que Colocar Apellido","Error",JOptionPane.ERROR_MESSAGE);
         
         
     }
    
    else if (t_dni.getText().isEmpty()) { 
         
          JOptionPane.showMessageDialog(null,"Ups... tienes que Colocar DNI","Error",JOptionPane.ERROR_MESSAGE);
         
         
    }    
        
 
    else if (t_us.getText().isEmpty()) { 
         
          JOptionPane.showMessageDialog(null,"Ups... tienes que Colocar UN USUARIO","Error",JOptionPane.ERROR_MESSAGE);
         
         
    }    
      
     else if (t_pass.getText().isEmpty()) { 
         
          JOptionPane.showMessageDialog(null,"Ups... tienes que Colocar UNA CONTRASEÑA","Error",JOptionPane.ERROR_MESSAGE);
         
         
    }   
     
    else if (c_tie.getSelectedItem()=="Escoja una") { 
         
          JOptionPane.showMessageDialog(null,"UPS... TIENE QUE ESCOJER UNA TIENDA","Error",JOptionPane.ERROR_MESSAGE);
         
     }   
     
    else if (c_us.getSelectedItem()=="Escoja un") { 
         
          JOptionPane.showMessageDialog(null,"UPS... TIENE QUE ESCOJER UNA TIPO DE USUARIO","Error",JOptionPane.ERROR_MESSAGE);  
          
          
   }else{
        
        if (JOptionPane.showConfirmDialog(null,"CONFIRMA QUE LOS DATOS ESTEN CORRECTOS","CONFIRMAR",1)==0){ 
    
        
        String d = t_dni.getText();
        consultar(d);  
        String nus = t_us.getText();
        consultar2(nus);
        SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
        acceso_java cc = new acceso_java ();
        Connection cn = cc.conxion();
        String sql="";
        String nom,ape,dni,us,pass,fecha,tus,tien;
        nom = t_nom.getText();
        ape = t_ape.getText();
        dni = t_dni.getText();
        us = t_us.getText();
        pass = t_pass.getText();
        tien = c_tie.getSelectedItem().toString();
        tus = c_us.getSelectedItem().toString();
        String fechad = sdf.format(t_fecha.getDate()); 
        
        
   
        sql= "INSERT INTO usuario (fecha,nom,ape,dni,nick,pass,tie,tuser) VALUES(?,?,?,?,?,?,?,?)";
        
        try{
            
          PreparedStatement pst = cn.prepareStatement(sql);
          
           pst.setString(1,fechad);
           pst.setString(2,nom);
           pst.setString(3,ape);
           pst.setString(4,dni);
           pst.setString(5,us);
           pst.setString(6,pass);
           pst.setString(7,tien);
           pst.setString(8,tus);
        
    
           int n=pst.executeUpdate();
           if (n>0){
               JOptionPane.showMessageDialog(null,"Registro Guardado con Exito");
               limpiar();
               
           }
                 
                 
        }catch (SQLException ex) {
            Logger.getLogger(n_clie.class.getName()).log(Level.SEVERE, null, ex);
            
          }
        }
      }
    }//GEN-LAST:event_cuActionPerformed

    private void t_dniKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_dniKeyTyped
        // TODO add your handling code here:
         char car = evt.getKeyChar();
        if( t_dni.getText().length()>=15 ) evt.consume();
        if(( car<'0' || car>'9' )) evt.consume();
    }//GEN-LAST:event_t_dniKeyTyped

    private void t_nomKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_nomKeyTyped
        // TODO add your handling code here:
        char c; 
        c=evt.getKeyChar(); 
        if(!(c<'0'||c>'9')) 
        evt.consume(); 
    }//GEN-LAST:event_t_nomKeyTyped

    private void t_apeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_apeKeyTyped
        // TODO add your handling code here:
        char c; 
        c=evt.getKeyChar(); 
        if(!(c<'0'||c>'9')) 
        evt.consume(); 
    }//GEN-LAST:event_t_apeKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new user().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox c_tie;
    private javax.swing.JComboBox c_us;
    private javax.swing.JButton cu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTextField t_ape;
    private javax.swing.JTextField t_dni;
    private com.toedter.calendar.JDateChooser t_fecha;
    private javax.swing.JTextField t_nom;
    private javax.swing.JPasswordField t_pass;
    private javax.swing.JTextField t_us;
    // End of variables declaration//GEN-END:variables
}
